"use client";
import "@/app/globals.css";
import type { Metadata } from "next";
import { Provider } from "react-redux";
import { store } from "@/store";
import "../firebase";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import useAuth from "@/hooks/IsAuth";
import Loader from "@/components/Loader/Loader";
export const metadata: Metadata = {
  title: "Live booblik",
  description: "Generated by programming genius",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isLoading } = useAuth();
  let app = null;
  if (isLoading) {
    app = <Loader />;
  } else {
    app = (
      <Provider store={store}>
        {children}
        <ToastContainer />
      </Provider>
    );
  }

  return (
    <html lang='="en"'>
      <body>{app}</body>
    </html>
  );
}
